AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: bootstrap 
      Runtime: provided.al2
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /
            Method: GET
      Environment:
        Variables:
          PARAM1: VALUE
    Metadata:
      BuildMethod: makefile