AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  BackFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: back/
      Handler: bootstrap 
      Runtime: provided.al2
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /api/{all+}
            Method: ANY
      Environment:
        Variables:
          DOMAIN_NAME: VALUE
          GITHUB_APP_ID: VALUE
          GITHUB_CLIENT_ID: VALUE
          GITHUB_SECRET: VALUE
    Metadata:
      BuildMethod: makefile
