FROM golang:alpine AS builder
MAINTAINER Goodgames
ENV GIN_MODE=release
WORKDIR /backend
COPY . .
COPY go.mod .
COPY go.sum .
RUN go mod download
RUN go build -o ./main .

FROM alpine:latest
WORKDIR ./src
COPY --from=builder /backend/main ./
EXPOSE $PORT
